#!/bin/sh

set -e

echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

apt-get update
apt-get install -y oracle-java8-installer

wget -nv -O atlas.jar https://github.com/Netflix/atlas/releases/download/v${ATLAS_VERSION}/atlas-${ATLAS_VERSION}-standalone.jar

apt-get clean
rm -rf /var/lib/apt/lists/*
